[CAR-69]Add new fields to Patient entity
DoubleHaoDev/carepulse-veins pull request #12
Opened 2024-09-17 14:27 UTC by Maxine311

add patient entity

2024-09-21 04:25 UTC, DoubleHaoDev requested changes

2024-09-21 04:25 UTC, DoubleHaoDev commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +  private String birthdate;
birthday column 的型別是ZonedDateTime
```suggestion
  private ZonedDateTime birthdate;
```

2024-09-21 04:25 UTC, DoubleHaoDev commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +  private Long address;
Address的型別是 String
```suggestion
  private String address;
```

2024-09-21 04:25 UTC, DoubleHaoDev commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +  private Long identificationType;
這裡的型別都忘記改囉～

2024-09-21 04:25 UTC, DoubleHaoDev commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +
新增fields後要順便一起改 toString, equals 以及hashCode method. 最簡單的方法可以把那三個方法刪掉後 直接滑鼠右鍵->generate -> equals() and hashcode() 還有 toString()

2024-09-26 02:58 UTC, Maxine311 commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +  private Long identificationType;
這個我想請問一下
是只要在schema上是varchar的在這邊都是string嗎？

2024-09-26 03:02 UTC, Maxine311 commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +
我想請問一下這三個是要作什麼的呢？

2024-09-27 00:34 UTC, DoubleHaoDev commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +
equals method是用來比較物件的,因為JAVA物件是存放在記憶體空間,如果沒有複寫這個方法的話即使內容物的值一樣一樣比較的時候會變成不一樣.override後比較只要內容值ㄧ樣及使在不同記憶體位置也能被當作一樣
hashcode method可以讓物件在某些條件下處理速度變快
toString是把物件文字化後會變成的字串,某些套件會使用到

2024-09-27 00:35 UTC, DoubleHaoDev commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +  private Long identificationType;
對～varchar都是String

2024-09-27 09:58 UTC, Maxine311 commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +  private Long identificationType;
好的

2024-09-27 09:58 UTC, Maxine311 commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +
了解

2024-09-30 00:46 UTC, DoubleHaoDev commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +  private String birthdate;
這個沒改到~ 不過我看一下這個應該是要改成LocalDate
```suggestion
  private LocalDate birthdate;
```

2024-09-30 06:17 UTC, Maxine311 commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +  private String birthdate;
不過這個我想請問一下
這兩個type都是要另外import的對嗎？
因為我看他有給我這個提示

2024-09-30 23:02 UTC, DoubleHaoDev commented on src/main/java/com/carefusion/carefusion_backend/model/entity/Patient.java
> +  private String birthdate;
沒錯～是要import才能用的

2024-09-30 23:03 UTC, DoubleHaoDev commented
LGTM

2024-09-30 23:03 UTC, DoubleHaoDev approved these changes

2024-09-30 23:04 UTC, merged